# Generated by Django 5.1.1 on 2024-09-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
